'use client';
import './globals.css';
import { Inter } from 'next/font/google';
import { AnimatePresence, motion } from 'framer-motion';
import { useState } from 'react';
import PageLoadingAnimation from '../components/PageLoadingAnimation';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Mats Fjeldstad',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [loading, setLoading] = useState(true);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-full min-h-screen w-full bg-gray-950 ">
          <div className="h-full min-h-screen w-full before:absolute before:inset-0 before:z-10 before:h-full before:w-full before:bg-dotted-spacing-3 before:bg-dotted-gray-400/10">
            <AnimatePresence mode="wait">
              {loading ? (
                <motion.div className="bg-none" key="loading">
                  <PageLoadingAnimation setLoading={setLoading} />
                </motion.div>
              ) : (
                <>
                  <Navbar />
                  <motion.div key="loaded">{children}</motion.div>
                </>
              )}
            </AnimatePresence>
          </div>
        </div>
      </body>
    </html>
  );
}
